package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.managerExceptions.ManagerValidateException;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static ru.yandex.javacourse.schedule.tasks.TaskStatus.*;

abstract class TaskManagerTest<T extends TaskManager> {
    protected T manager;

    protected abstract T createManager();

    @BeforeEach
    protected void setUp() {
        manager = createManager();
    }

    @Test
    @DisplayName("Добавление новой задачи и проверка ее сохранения")
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }


    @Test
    @DisplayName("Автогенерация ID для задач")
    public void testAddTaskAutogeneratedId() {
        Task task0 = new Task("Test 1", "Testing task 1", NEW);
        Task task1 = new Task("Test 2", "Testing task 2", NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "autogenerated id should be 2");
    }

    @Test
    @DisplayName("Проверка неизменности задачи после добавления")
    public void checkTaskNotChangedAfterAddTask() {
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = NEW;
        Task task1before = new Task(name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(task1after.getId(), task1before.getId());
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    @DisplayName("Добавление всех типов задач")
    public void testAddAllTasks() {
        Task task0 = new Task("Test 1", "Testing task 1", NEW);
        Task task1 = new Task("Test 2", "Testing task 2", NEW);
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        manager.addNewSubtask(subtask1);
        assertEquals(1, manager.getEpics().size(), "All epics should be added");
        assertEquals(1, manager.getSubtasks().size(), "All subtasks should be added");
        assertEquals(2, manager.getTasks().size(), "All tasks should be added");
    }

    @Test
    @DisplayName("Обновление обычной задачи")
    public void testUpdateTask() {
        String name = "Test 1";
        String changedName = "Test 2";
        String description = "Testing task 1";
        TaskStatus status = NEW;
        Task task = new Task(name, description, status);
        manager.addNewTask(task);
        task.setName(changedName);
        manager.updateTask(task);
        assertEquals(task.getName(), changedName);
        assertEquals(task.getDescription(), description);
    }

    @Test
    @DisplayName("Обновление эпика")
    public void testUpdateEpic() {
        String name = "Test 1";
        String changedName = "Test 2";
        String description = "Testing epic 1";
        Epic epic = new Epic(name, description);
        manager.addNewEpic(epic);
        epic.setName(changedName);
        manager.updateEpic(epic);
        assertEquals(epic.getName(), changedName);
        assertEquals(epic.getDescription(), description);
    }

    @Test
    @DisplayName("Обновление подзадачи")
    public void testUpdateSubtask() {
        String name = "Test 1";
        String changedName = "Test 2";
        String description = "Testing epic 1";
        Epic epic = new Epic(name, description);
        manager.addNewEpic(epic);
        Subtask subtask = new Subtask(name, description, NEW, epic.getId());
        manager.addNewSubtask(subtask);
        subtask.setName(changedName);
        manager.updateSubtask(subtask);
        assertEquals(subtask.getName(), changedName);
        assertEquals(subtask.getDescription(), description);
    }

    @Test
    @DisplayName("Удаление эпиков и связанных подзадач")
    public void testDeleteEpics() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        Epic epic2 = new Epic("Epic 2", "Testing epic 2");
        manager.addNewTask(new Task("Test 1", "Testing task 1", NEW));
        manager.addNewTask(new Task("Test 2", "Testing task 2", NEW));
        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        manager.deleteEpic(epic1.getId());
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic2.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(1, manager.getEpics().size(), "One epic should be removed");
        assertEquals(1, manager.getSubtasks().size(), "One subtask should be removed");
        assertEquals(2, manager.getTasks().size(), "Tasks should not be removed");
        manager.addNewEpic(new Epic("Epic 2", "Testing epic 2"));
        manager.deleteEpics();
        assertEquals(0, manager.getEpics().size(), "All epic should be removed");
        assertEquals(0, manager.getSubtasks().size(), "All subtask should be removed");
        assertEquals(2, manager.getTasks().size(), "Tasks should not be removed");
    }


    @Test
    @DisplayName("Удаление задач")
    public void testDeleteTasks() {
        Task task1 = new Task("Test 1", "Testing task 1", NEW);
        Task task2 = new Task("Test 2", "Testing task 2", NEW);
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        Epic epic2 = new Epic("Epic 2", "Testing epic 2");
        manager.addNewTask(task1);
        manager.addNewTask(task2);
        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic2.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        manager.deleteTask(task1.getId());
        assertEquals(1, manager.getTasks().size(), "One task should be removed");
        assertEquals(2, manager.getEpics().size(), "Epics should not be removed");
        assertEquals(2, manager.getSubtasks().size(), "Subtasks should not be removed");

        manager.addNewTask(new Task("Test 1", "Testing task 1", NEW));
        manager.deleteTasks();
        assertEquals(0, manager.getTasks().size(), "All task should be removed");
        assertEquals(2, manager.getEpics().size(), "Epics should not be removed");
        assertEquals(2, manager.getSubtasks().size(), "Subtasks should not be removed");
    }

    @Test
    @DisplayName("Удаление подзадач")
    public void testDeleteSubtasks() {
        Task task1 = new Task("Test 1", "Testing task 1", NEW);
        Task task2 = new Task("Test 2", "Testing task 2", NEW);
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        Epic epic2 = new Epic("Epic 2", "Testing epic 2");
        manager.addNewTask(task1);
        manager.addNewTask(task2);
        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic2.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        manager.deleteSubtask(subtask1.getId());
        assertEquals(1, manager.getSubtasks().size(), "One subtask should be removed");
        assertEquals(2, manager.getTasks().size(), "Tasks should be removed");
        assertEquals(2, manager.getEpics().size(), "Epics should not be removed");

        manager.addNewSubtask(new Subtask("Test 1", "Testing task 1", NEW, epic1.getId()));
        manager.deleteSubtasks();
        assertEquals(0, manager.getSubtasks().size(), "All subtask should be removed");
        assertEquals(2, manager.getEpics().size(), "Epics should not be removed");
        assertEquals(2, manager.getTasks().size(), "Tasks should not be removed");
    }

    @Test
    @DisplayName("Статус эпика со всеми подзадачами со статусом NEW")
    public void testEpicWithNewSubtasks() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic1.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(NEW, manager.getEpic(epicId).getStatus());
    }

    @Test
    @DisplayName("Статус эпика со всеми подзадачами со статусом DONE")
    public void testEpicWithDoneSubtasks() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", DONE, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", DONE, epic1.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(DONE, manager.getEpic(epicId).getStatus());
    }

    @Test
    @DisplayName("Статус эпика с подзадачами со статусом DONE и NEW")
    public void testEpicWithDoneAndNewSubtasks() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", DONE, epic1.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(IN_PROGRESS, manager.getEpic(epicId).getStatus());
    }

    @Test
    @DisplayName("Статус эпика с подзадачами со статусом DONE и NEW")
    public void testEpicWithInProgressSubtasks() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", IN_PROGRESS, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", IN_PROGRESS, epic1.getId());
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(IN_PROGRESS, manager.getEpic(epicId).getStatus());
    }

    @Test
    @DisplayName("Подзадачи имеют связанный эпик")
    public void testSubtasksHaveEpicId() {
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic1);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", IN_PROGRESS, epic1.getId());
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", IN_PROGRESS, epic1.getId());
        Subtask subtaskWithoutEpic = new Subtask("Test 2", "Testing task 2", IN_PROGRESS, 33);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertNull(manager.addNewSubtask(subtaskWithoutEpic));
        assertEquals(epicId, subtask1.getEpicId());
        assertEquals(epicId, subtask2.getEpicId());
    }

    @Test
    @DisplayName("Время выполнения эпика - сумма времени выполнения всех его подзадач")
    public void testUpdateEpicTimes() {
        LocalDateTime localDateTime = LocalDateTime.now();
        int min = 90;
        int min2 = 40;
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        Epic epic2 = new Epic("Epic 2", "Testing epic 2");
        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId(), min, localDateTime);
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic1.getId(), min2, localDateTime.plusMinutes(min));
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(localDateTime.plusMinutes(min).plusMinutes(min2), manager.getEpic(epic1.getId()).getEndTime().get());
    }

    @Test
    @DisplayName("При конфликте времени выпорлнения")
    public void testUpdateEpicTimesThrowExeption() {
        LocalDateTime localDateTime = LocalDateTime.now();
        int min = 90;
        int min2 = 40;
        Epic epic1 = new Epic("Epic 1", "Testing epic 1");
        Epic epic2 = new Epic("Epic 2", "Testing epic 2");
        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        Subtask subtask1 = new Subtask("Test 1", "Testing task 1", NEW, epic1.getId(), min, localDateTime);
        Subtask subtask2 = new Subtask("Test 2", "Testing task 2", NEW, epic1.getId(), min2, localDateTime.plusMinutes(min));
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        assertEquals(localDateTime.plusMinutes(min).plusMinutes(min2), manager.getEpic(epic1.getId()).getEndTime().get());
    }

    @Test
    @DisplayName("При конфликте времени выполнения должен выбросится exception")
    public void validateNoTimeOverlap() {
        LocalDateTime localDateTime = LocalDateTime.now();
        int min = 90;
        Task taskBefore = new Task("Test 1", "Testing task 1", TaskStatus.NEW, min, localDateTime);
        Task taskOverlap = new Task("Test 3", "Testing task 3", TaskStatus.NEW, min, localDateTime);
        manager.addNewTask(taskBefore);
        assertThrows(ManagerValidateException.class, () -> manager.addNewTask(taskOverlap));
    }

    @Test
    @DisplayName("Возвращается сортированный по времени список задач")
    void testGetPrioritizedTasks() {
        LocalDateTime localDateTime = LocalDateTime.now();
        int min = 90;
        Task taskBefore = new Task("Test 1", "Testing task 1", TaskStatus.NEW, min, localDateTime);
        Task taskAfter = new Task("Test 2", "Testing task 2", TaskStatus.NEW, min, localDateTime.plusMinutes(min));
        manager.addNewTask(taskBefore);
        manager.addNewTask(taskAfter);
        List<Task> prioritized = manager.getPrioritizedTasks();
        assertEquals(taskBefore, prioritized.get(0));
        assertEquals(taskAfter, prioritized.get(1));
    }
}

